---
title: "EDA"
output:   
  html_document:
    toc: true
    toc_float: true
fontsize: 12pt
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(plotly)
library(cowplot)
library(RColorBrewer)

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = F,
  fig.height = 5
)
```

```{r read_avo}
avo_df = 
  read_csv("data/avocado.csv") %>% 
  janitor::clean_names() %>% 
  select(-1) %>% 
  separate(date, c("year", "month", "day"), remove = FALSE) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day)
  ) %>% 
  rename(
    small = x4046,
    large = x4225,
    extra_large = x4770,
  ) 


gdp_df = read_csv("data/gdp-by-state.csv") %>% select(-1)
```

Preview the cleaned avocado dataset.

```{r look_avocado}
avo_df %>% head() %>% knitr::kable()

#sum(is.na(avo_df))

```

Preview the gdp dataset.
```{r look_gdp}
gdp_df %>% head() %>% knitr::kable()

#sum(is.na(gdp_df))
```


# Avocado dataset

```{r price_dist, include=FALSE}
price_dist = 
avo_df %>% 
  ggplot(aes(x = average_price))

price_dist + 
  geom_histogram(aes(fill = type), alpha = 0.3,binwidth = 0.1) +
  labs(
    title = "United States Avocado Price Distribution (2015-2018)",
    x = "Average Price",
    y = "Count",
    fill = "Type"
    ) 

price_dist + 
  geom_density(aes(color = type),alpha = 0.3) +
  labs(
    title = "United States Avocado Price Distribution (2015-2018)",
    x = "Average Price",
    y = "Density",
    color = "Type"
    ) 
```

Checking the Distribution of the avocado price, we found that the prices of the two types of avocado, conventional and organic, are generally normally distributed, with organic avocado prices being much higher. 
```{r}
conv_color = "#F08080"
org_color = "#BDB76B"

  avo_df %>% 
  mutate(type = recode(type, "conventional"="Conventional", "organic"="Organic")) %>% 
  ggplot(aes(x = average_price, y = ..density.., fill = type, color = type)) +
  geom_histogram(alpha = 0.4, binwidth = 0.1) +
  geom_density(alpha = 0.3) +
  labs(
    title = "United States Avocado Price Distribution (2015-2018)",
    x = "Average Price",
    y = "Density",
    fill = "Type"
    ) +
  guides(color = FALSE) + scale_fill_manual(values=c(conv_color, org_color)) + scale_color_manual(values=c(conv_color, org_color))


```



# GDP dataset

Preview the GDP distribution.
```{r gdp_dist}
gdp_dist = 
  gdp_df %>% 
  pivot_longer(
    "2013":"2017",
    names_to = "year",
    values_to = "gdp"
  )


gdp_dist %>% 
  filter(Area != "United States") %>% 
  ggplot(aes(x = gdp))+
  geom_histogram(aes(fill = year), alpha = .4, binwidth = 3000)+
  labs(
    title = "United States GDP Distribution (2013-2017)",
    x = "GDP",
    y = "Density",
    fill = "Year"
    ) 
#+ scale_fill_brewer(palette = "Paired")
```

```{r}
gdp_dist %>% 
  filter(Area != "United States") %>% 
  mutate(
    Area = fct_reorder(Area, gdp)
  ) %>% 
  ggplot(aes(x = gdp, y = Area, fill = Area))+
  geom_bar(position = "dodge", stat = "identity", alpha=.5)+
  theme(legend.position = "none")+
  labs(
    title = "United States GDP Ranking (2013-2017)",
    x = "GDP",
    y = "Area"
    ) +
  facet_grid(~year)+
  theme(plot.title=element_text(hjust=0.5), axis.text.x = element_text(angle = 45)) +
  theme(axis.text.y = element_text(size = 5)) 
```


