---
title: "p8105_final_proposal"
author: "Beibei Cao, Chenxi Liu, Renjie Wei, Weixi Chen"
date: "11/6/2020"
output: html_document
---

This is our proposal for p8105 final project.

**Group members**:\
Beibei Cao (bc2918)\
Chenxi Liu (cl4044)\
Renjie Wei (rw2844)\
Weixi Chen (wc2750)\

**Tentative project title**:\

**Motivation**:\
Our project intends to analyze and visualize the data from

**Intended final products**:\
The final product will be a well-formatted website, incluidng video presentation, written report, and the display of our data source, data analysis and interactivity visulization.

**Data sources**:\

**Planned analyses / visualizations / coding challenges**:\
The data will be firstly loaded from websites through `rvest` and `httr` packages. Then, the data will be manipulated through `tidyverse`, `stringr`, and `forcat` packages, and the exploratory analysis will be conducted for statistics summaries through `group_by` and `summary` functions. Visualizations will be used to show the trends and associations of the variables through `ggplot`. In addition, the plots will be displayed for interactivity on websites through `plotly` and `flexdashboard`.

**Planned timeline**:\