---
title: "Prediction Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r,include=FALSE,message=FALSE,echo=FALSE}
library(tidyverse)
library(prophet)
knitr::opts_chunk$set(
 echo = FALSE,
 fig.width = 7, 
 fig.height = 5,
 fig.asp = 0.6,
 out.width = "60%")
theme_set(theme_bw() + 
          theme(legend.position = "bottom",
                legend.title = element_blank(),
                plot.title = element_text(hjust = 0.5, size = 15),
                plot.subtitle = element_text(hjust = 0.5, size = 12)))

avo_df = 
  read_csv("data/avocado.csv") %>% 
  janitor::clean_names() %>% 
  select(-1) %>% 
  separate(date, c("year", "month", "day"), remove = FALSE) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day)
  ) %>% 
  rename(
    small = x4046,
    large = x4225,
    extra_large = x4770,
  ) 
```


## Use Prophet Machine Learning Model to Predict Price

Prophet is a great times-series prediction model. According to the graph below, we know where the average price will be at in the coming year. 

```{r, cache=TRUE, message=FALSE}
avo_df_sub = avo_df %>% 
  filter(region == "TotalUS") %>%
  select(date, average_price) %>%
  rename(ds = date, y = average_price) %>%
  mutate(ds = as.factor(ds))

mod <- prophet(avo_df_sub,  changepoint.prior.scale = 0.5)
future <- make_future_dataframe(mod, periods = 365)
# tail(future)
forecast <- predict(mod, future)
plot(mod, forecast, xlabel = "Date",
ylabel = "Average Price",
title = "Prediction of prices in one year")
```

## Forecast Components

The two graphs belows tells us the trend, yearly of the time series and how components of the model affect our predictions.
```{r, cache=TRUE, message=FALSE}
prophet_plot_components(mod, forecast)
```



