---
title: "Correlation"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
library(tidyverse)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
echo = FALSE,
message = FALSE,
warning = FALSE
)
theme_set(theme_minimal() + 
            theme(legend.position = "bottom", 
                  legend.title = element_blank(),
                  plot.title = element_text(hjust = 0.5, size = 15),
                  plot.subtitle = element_text(hjust = 0.5, size = 12)))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r include = FALSE}
# load basic avocado dataframe
avo_df = read_csv("data/avocado.csv") %>%
  janitor::clean_names() %>%
  select(-1) %>% 
  separate(date, c("year", "month", "day"), remove = FALSE) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day)
  ) %>% 
  rename(
    small = x4046,
    large = x4225,
    extra_large = x4770,
  ) 
```

```{r include = FALSE}
# tidy avo_df for regression analysis
df = 
  avo_df %>%
  filter(year != 2018,
         region %in% c("California", "West", "Plains", "SouthCentral", "GreatLakes", "Northeast", "Midsouth", "Southeast")) %>%
  #mutate(quarter = if_else(month %in% c(1,2,3), "quarter1", if_else(month %in% c(4,5,6), "quarter2", if_else(month %in% c(7,8,9), "quarter3", "quarter4")))) %>%
  mutate(quarter = if_else(month %in% c(1,2,3), 1, if_else(month %in% c(4,5,6), 2, if_else(month %in% c(7,8,9), 3,4))))%>% 
  select(year, quarter, type, region, average_price) %>%
  group_by(year, quarter, type, region) %>%
  summarise(quarterly_average_price = mean(average_price)) %>% 
  mutate(
    type = recode(type, "conventional"=1, "organic"=0)
  )

df$California = ifelse(df$region=="California", 1,0)
df$West = ifelse(df$region=="West", 1,0)
df$Plains = ifelse(df$region=="Plains", 1,0)
df$SouthCentral = ifelse(df$region=="SouthCentral", 1,0)
df$GreatLakes = ifelse(df$region=="GreatLakes", 1,0)
df$NorthEast = ifelse(df$region=="Northeast", 1,0)
df$MidSouth = ifelse(df$region=="Midsouth", 1,0)
df$SouthEast = ifelse(df$region=="Southeast", 1,0)

#df$Jan_Mar = ifelse(df$quarter=="quarter1", 1,0)
#df$Apr_Jun = ifelse(df$quarter=="quarter2", 1,0)
#df$Jul_Sep = ifelse(df$quarter=="quarter3", 1,0)
#df$Oct_Dec = ifelse(df$quarter=="quarter4", 1,0)

df_1 = df %>% 
  rename(price = quarterly_average_price) %>% 
  select(-region, -quarter)

```




```{r fig.height=5, fig.width=4.1}
cormat <- cor(df_1)

library(reshape2)
melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()+
  theme(axis.text.x=element_text(angle=90)) +  
  labs(title="", x="", y="", color = "")
```

